sudo: required
language: ruby
rvm:
- 2.2.3
bundler_args: --without development production

env:
  - ES_VERSION=2.4.5 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz

before_install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - sleep 30

before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:create db:migrate RAILS_ENV=test
- export RECAPTCHA_SECRET_KEY=6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
- export RECAPTCHA_SITE_KEY=6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
- sleep 5 # To make sure Elasticsearch instance is ready

script:
- curl -X GET http://localhost:9200/
- bundle exec rspec spec/
- bundle exec rake test
